plugins {
	id 'net.fabricmc.fabric-loom' version '1.17-SNAPSHOT' apply false
	id 'net.fabricmc.fabric-loom-remap' version '1.17-SNAPSHOT' apply false

	id 'maven-publish'
}

base {
	archivesName = project.archives_base_name
}

repositories {

}

if (stonecutter.compare(stonecutter.current.version, "26.1") < 0) {
	apply plugin: 'net.fabricmc.fabric-loom-remap'
} else {
	apply plugin: 'net.fabricmc.fabric-loom'
}

loom {
	runConfigs.all {
		ideConfigGenerated true // Run configurations are not created for subprojects by default
		runDir "../../run" // Use a shared run folder and just create separate worlds
	}
}

fabricApi {
	configureDataGeneration()
}

dependencies {
	minecraft "com.mojang:minecraft:${property('deps.minecraft')}"

	if (stonecutter.compare(stonecutter.current.version, "26.1") < 0) {
		mappings "net.fabricmc:yarn:${property('deps.yarn_mappings')}:v2"
		modImplementation "net.fabricmc:fabric-loader:${property('deps.fabric_loader')}"
	} else {
		implementation "net.fabricmc:fabric-loader:${property('deps.fabric_loader')}"
	}
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 17
}

java {
	withSourcesJar()

	if (stonecutter.compare(stonecutter.current.version, "26.1") >= 0) {
		sourceCompatibility = JavaVersion.VERSION_25
		targetCompatibility = JavaVersion.VERSION_25
	} else if (stonecutter.compare(stonecutter.current.version, "1.21") >= 0) {
		sourceCompatibility = JavaVersion.VERSION_21
		targetCompatibility = JavaVersion.VERSION_21
	} else {
		sourceCompatibility = JavaVersion.VERSION_17
		targetCompatibility = JavaVersion.VERSION_17
	}
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.base.archivesName.get()}"}
	}
}